# Generated by Django 5.0.7 on 2024-07-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_user_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pass_field',
            new_name='password',
        ),
    ]
