# Generated by Django 5.0.7 on 2024-07-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_pass_field_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='node_gateway',
            field=models.IntegerField(unique=True),
        ),
    ]
