# Generated by Django 5.0.7 on 2024-07-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_gateway_node_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGatewayOneDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('node_gateway', models.IntegerField()),
                ('node', models.CharField(blank=True, max_length=255, null=True)),
                ('date_create', models.DateTimeField()),
                ('node_data', models.JSONField()),
            ],
            options={
                'db_table': 'data_gateway_one_day',
            },
        ),
    ]
