# Generated by Django 5.0.7 on 2024-07-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_datagatewayoneday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagatewayoneday',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
