# Generated by Django 5.0.7 on 2024-07-25 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_datagatewayoneday_date_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('node_data', models.JSONField()),
                ('node_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_report_gateway', to='myapp.gateway')),
            ],
            options={
                'db_table': 'history_report',
            },
        ),
    ]
