# Generated by Django 5.0.7 on 2024-08-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_historyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='node_data',
            field=models.JSONField(default=dict),
        ),
    ]
