# Generated by Django 5.0.7 on 2024-08-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_gateway_node_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagatewayoneday',
            name='date_create',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detailreportnode',
            name='dateCreate',
            field=models.TextField(),
        ),
    ]
