# Generated by Django 5.0.7 on 2024-08-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_datagatewayoneday_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dateCreate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='dateCreate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='dateCreate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='dateCreate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rule',
            name='dateCreate',
            field=models.TextField(),
        ),
    ]
